version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19

    commands:
      - pip install --upgrade pip aws-sam-cli
      - pip install -r requirements.txt

  post_build:
    commands:
      - docker --info
      - sam --version
      - pytest -vvv --capture=tee-sys tests/integration/build_invoke/test_build_invoke.py -n 8
